<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="camera_with_gripper" params="">
  <xacro:property name="gripper_offset" value="0.005" />
  <xacro:property name="gripper_lenght" value="0.18" />
  <xacro:property name="gripper_radius" value="0.0375" />
  
  <!-- parameters to allign camera support frame with camera_support link -->
  <xacro:property name="camera_support_origin_x" value="0.055" />
  <xacro:property name="camera_support_origin_y" value="-0.0375" />
  <xacro:property name="camera_support_origin_z" value="0.019" />
  <xacro:property name="camera_support_origin_p" value="3.14" />

    <joint name="camera_support_joint" type="fixed">
      <parent link="flange"/>
      <child link="camera_support"/>
      <origin rpy="0 0 2.355" xyz="0 0 0.004"/>
    </joint>

    <link name="camera_support">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.039" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
      </inertial>
      <visual>
        <origin xyz="${camera_support_origin_x} ${camera_support_origin_y} ${camera_support_origin_z}" rpy="0 ${camera_support_origin_p} 0" />
        <geometry>
          <mesh filename="package://tennisball_demo_v2/robot_description/meshes/cameraD455_UR5e.STL" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 0.8 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${camera_support_origin_x*1.1} ${camera_support_origin_y*1.1} ${camera_support_origin_z}" rpy="0 ${camera_support_origin_p} 0" />
        <geometry>
          <mesh filename="package://tennisball_demo_v2/robot_description/meshes/cameraD455_UR5e.STL" scale="0.0011 0.0011 0.001"/>
        </geometry>
      </collision>
    </link>

    <joint name="mygripper_joint" type="fixed">
      <parent link="camera_support"/>
      <child link="mygripper"/>
      <origin rpy="0 0 0" xyz="0 0 0.094"/>
    </joint>

    <link name="mygripper">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.176" />
        <inertia ixx="0.0005" ixy="0.0" ixz="0.0" iyy="0.0005" iyz="0.0" izz="0.0001" />
      </inertial>
      <visual>
        <geometry>
          <cylinder length="${gripper_lenght}" radius="${gripper_radius}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${gripper_lenght}" radius="${gripper_radius+gripper_offset}"/>
        </geometry>
      </collision>
    </link>

    <joint name="tcp_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.09"/>
      <parent link="mygripper"/>
      <child link="tool0"/>
    </joint>
    
  </xacro:macro>

</robot>